== Dukes-Liberty

[[summary]]
=== Summary

The dukes-liberty application provides simple examples demonstrating various features of the https://microprofile.io[MicroProfile] programming model using the https://openliberty.io[Open Liberty] application server.

[[requirements]]
=== Requirements
* https://maven.apache.org/install.html[Maven]
* Java 8 or 11: Any compliant JDK should work.
** https://adoptopenjdk.net/index.html[AdoptOpenJDK 8 or 11 (OpenJ9 preferred, Hotspot also available)]
** http://www.ibm.com/developerworks/java/jdk/[Java 8 JDK from IBM (AIX, Linux, z/OS, IBM i)]
** http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java 8 JDK from Oracle]

[[configuration]]
=== Configuration
The application is configured to provide various technologies and features. These capabilities are provided through dependencies in the `pom.xml` file and Open Liberty features enabled in the server config file found in `src/main/liberty/config/server.xml`.

[[project-contents]]
=== Project contents
The context root can be set in the `src/main/webapp/WEB-INF/ibm-web-ext.xml` file. The ports are set in the `pom.xml` file.

 - **MicroProfile** : The http://microprofile.io/[MicroProfile project] is an open community with the aim of optimizing Enterprise Java for a microservices architecture.
MicroProfile will be evolving with guidance from the community.
For a quick hands-on MicroProfile experience, check out the https://openliberty.io/guides/?search=microprofile[Open Liberty Guides].
For more complete feature documentation, see the https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_microprofile.html[MicroProfile programming model section] in the IBM Knowledge Center.
If you want to share your thoughts, you can post straight to the https://groups.google.com/forum/#!forum/microprofile[MicroProfile Google group].

[[run]]
=== Run

To build and run the application:
----
mvn clean install
mvn liberty:run-server  (ctrl-c ends the server)
----

OR ...

To run application as a "fat jar":
----
mvn clean install -P runnable
java -jar target/dukes-liberty.jar
----

[[endpoints]]
=== Endpoints

The context root can be set in the `src/main/webapp/WEB-INF/ibm-web-ext.xml` file.
The application path root can be set in `ApplicationConfig.java`.
The ports are set in the `pom.xml` file.

 - Dukes-Liberty Endpoint:  http://localhost:9080/
 - Dukes-Liberty warmHello API Endpoint:  http://localhost:9080/warmHello
 - MicroProfile Health Endpoint:  http://localhost:9080/health
 - MicroProfile Metrics Endpoint:  http://localhost:9080/metrics
 - MicroProfile Metrics Application Endpoint:  http://localhost:9080/metrics/application
 - MicroProfile OpenAPI Endpoint:  http://localhost:9080/openapi
 - MicroProfile OpenAPI UI:  http://localhost:9080/openapi/ui/
